version: '3'

services:
  worker:
    image: amsdard.io/exmachina/playlive-demo-worker:2.0
    container_name: worker.demo-app.playlive.docker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_NAME=queue
      - REDIS_QUEUE=playlive
      - WORKERS=1
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=admin
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=12345
    networks:
      - global
    stdin_open: true
    tty: true
    restart: always

  app:
    image: amsdard.io/exmachina/playlive-demo-app:2.0
    container_name: demo-app.playlive.docker
    environment:
      - PORT=80
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_NAME=queue
      - REDIS_QUEUE=playlive
    networks:
      - global
    stdin_open: true
    tty: true
    restart: always

networks:
  global:
    external: true
